// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/namenode/namenode.proto

package namenode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldFileName string `protobuf:"bytes,1,opt,name=OldFileName,proto3" json:"OldFileName,omitempty"`
	NewFileName string `protobuf:"bytes,2,opt,name=NewFileName,proto3" json:"NewFileName,omitempty"`
}

func (x *RenameReq) Reset() {
	*x = RenameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReq) ProtoMessage() {}

func (x *RenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReq.ProtoReflect.Descriptor instead.
func (*RenameReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *RenameReq) GetOldFileName() string {
	if x != nil {
		return x.OldFileName
	}
	return ""
}

func (x *RenameReq) GetNewFileName() string {
	if x != nil {
		return x.NewFileName
	}
	return ""
}

type RenameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *RenameResp) Reset() {
	*x = RenameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResp) ProtoMessage() {}

func (x *RenameResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResp.ProtoReflect.Descriptor instead.
func (*RenameResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *RenameResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IsDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
}

func (x *IsDirReq) Reset() {
	*x = IsDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDirReq) ProtoMessage() {}

func (x *IsDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDirReq.ProtoReflect.Descriptor instead.
func (*IsDirReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{2}
}

func (x *IsDirReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type IsDirResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *IsDirResp) Reset() {
	*x = IsDirResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDirResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDirResp) ProtoMessage() {}

func (x *IsDirResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDirResp.ProtoReflect.Descriptor instead.
func (*IsDirResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{3}
}

func (x *IsDirResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetDataNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDataNodesReq) Reset() {
	*x = GetDataNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataNodesReq) ProtoMessage() {}

func (x *GetDataNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataNodesReq.ProtoReflect.Descriptor instead.
func (*GetDataNodesReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{4}
}

type GetDataNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataNodeList []string `protobuf:"bytes,1,rep,name=DataNodeList,proto3" json:"DataNodeList,omitempty"`
}

func (x *GetDataNodesResp) Reset() {
	*x = GetDataNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataNodesResp) ProtoMessage() {}

func (x *GetDataNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataNodesResp.ProtoReflect.Descriptor instead.
func (*GetDataNodesResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataNodesResp) GetDataNodeList() []string {
	if x != nil {
		return x.DataNodeList
	}
	return nil
}

type StatDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *StatDataReq) Reset() {
	*x = StatDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDataReq) ProtoMessage() {}

func (x *StatDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDataReq.ProtoReflect.Descriptor instead.
func (*StatDataReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{6}
}

func (x *StatDataReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type StatDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *StatDataResp) Reset() {
	*x = StatDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDataResp) ProtoMessage() {}

func (x *StatDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDataResp.ProtoReflect.Descriptor instead.
func (*StatDataResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{7}
}

func (x *StatDataResp) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

type DeleteDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *DeleteDataReq) Reset() {
	*x = DeleteDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataReq) ProtoMessage() {}

func (x *DeleteDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataReq.ProtoReflect.Descriptor instead.
func (*DeleteDataReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDataReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *DeleteDataResp) Reset() {
	*x = DeleteDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResp) ProtoMessage() {}

func (x *DeleteDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResp.ProtoReflect.Descriptor instead.
func (*DeleteDataResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDataResp) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

type DataNodeInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host        string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ServicePort string `protobuf:"bytes,2,opt,name=servicePort,proto3" json:"servicePort,omitempty"`
}

func (x *DataNodeInstance) Reset() {
	*x = DataNodeInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataNodeInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNodeInstance) ProtoMessage() {}

func (x *DataNodeInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNodeInstance.ProtoReflect.Descriptor instead.
func (*DataNodeInstance) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{10}
}

func (x *DataNodeInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DataNodeInstance) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

type NameNodeMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId        string              `protobuf:"bytes,1,opt,name=blockId,proto3" json:"blockId,omitempty"`
	BlockAddresses []*DataNodeInstance `protobuf:"bytes,2,rep,name=blockAddresses,proto3" json:"blockAddresses,omitempty"`
}

func (x *NameNodeMetaData) Reset() {
	*x = NameNodeMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameNodeMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameNodeMetaData) ProtoMessage() {}

func (x *NameNodeMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameNodeMetaData.ProtoReflect.Descriptor instead.
func (*NameNodeMetaData) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{11}
}

func (x *NameNodeMetaData) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NameNodeMetaData) GetBlockAddresses() []*DataNodeInstance {
	if x != nil {
		return x.BlockAddresses
	}
	return nil
}

type GetBlockSizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request bool `protobuf:"varint,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetBlockSizeRequest) Reset() {
	*x = GetBlockSizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockSizeRequest) ProtoMessage() {}

func (x *GetBlockSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockSizeRequest.ProtoReflect.Descriptor instead.
func (*GetBlockSizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlockSizeRequest) GetRequest() bool {
	if x != nil {
		return x.Request
	}
	return false
}

type GetBlockSizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockSize uint64 `protobuf:"varint,1,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
}

func (x *GetBlockSizeResponse) Reset() {
	*x = GetBlockSizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockSizeResponse) ProtoMessage() {}

func (x *GetBlockSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockSizeResponse.ProtoReflect.Descriptor instead.
func (*GetBlockSizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlockSizeResponse) GetBlockSize() uint64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type ReadRequst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *ReadRequst) Reset() {
	*x = ReadRequst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequst) ProtoMessage() {}

func (x *ReadRequst) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequst.ProtoReflect.Descriptor instead.
func (*ReadRequst) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{14}
}

func (x *ReadRequst) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{15}
}

func (x *ReadResponse) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize uint64 `protobuf:"varint,2,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{16}
}

func (x *WriteRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *WriteRequest) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{17}
}

func (x *WriteResponse) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

var File_proto_namenode_namenode_proto protoreflect.FileDescriptor

var file_proto_namenode_namenode_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x22, 0x4f, 0x0a, 0x09, 0x52, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x6c, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x6c,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65, 0x77,
	0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x52,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x49, 0x73, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x09, 0x49,
	0x73, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x36, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f,
	0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x2b, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f,
	0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x48, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x71, 0x0a, 0x10, 0x4e, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x28, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a,
	0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x46,
	0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x60, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x92, 0x04, 0x0a, 0x0f, 0x4e, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x08, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x2e, 0x6e, 0x61, 0x6d, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x08,
	0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x6e, 0x61, 0x6d, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x32, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x12, 0x13, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x49, 0x73, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x49, 0x73, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x06, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x16, 0x5a,
	0x14, 0x67, 0x6f, 0x2d, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_namenode_namenode_proto_rawDescOnce sync.Once
	file_proto_namenode_namenode_proto_rawDescData = file_proto_namenode_namenode_proto_rawDesc
)

func file_proto_namenode_namenode_proto_rawDescGZIP() []byte {
	file_proto_namenode_namenode_proto_rawDescOnce.Do(func() {
		file_proto_namenode_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_namenode_namenode_proto_rawDescData)
	})
	return file_proto_namenode_namenode_proto_rawDescData
}

var file_proto_namenode_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_namenode_namenode_proto_goTypes = []interface{}{
	(*RenameReq)(nil),            // 0: namenode_.RenameReq
	(*RenameResp)(nil),           // 1: namenode_.RenameResp
	(*IsDirReq)(nil),             // 2: namenode_.IsDirReq
	(*IsDirResp)(nil),            // 3: namenode_.IsDirResp
	(*GetDataNodesReq)(nil),      // 4: namenode_.GetDataNodesReq
	(*GetDataNodesResp)(nil),     // 5: namenode_.GetDataNodesResp
	(*StatDataReq)(nil),          // 6: namenode_.StatDataReq
	(*StatDataResp)(nil),         // 7: namenode_.StatDataResp
	(*DeleteDataReq)(nil),        // 8: namenode_.DeleteDataReq
	(*DeleteDataResp)(nil),       // 9: namenode_.DeleteDataResp
	(*DataNodeInstance)(nil),     // 10: namenode_.DataNodeInstance
	(*NameNodeMetaData)(nil),     // 11: namenode_.NameNodeMetaData
	(*GetBlockSizeRequest)(nil),  // 12: namenode_.GetBlockSizeRequest
	(*GetBlockSizeResponse)(nil), // 13: namenode_.GetBlockSizeResponse
	(*ReadRequst)(nil),           // 14: namenode_.ReadRequst
	(*ReadResponse)(nil),         // 15: namenode_.ReadResponse
	(*WriteRequest)(nil),         // 16: namenode_.WriteRequest
	(*WriteResponse)(nil),        // 17: namenode_.WriteResponse
}
var file_proto_namenode_namenode_proto_depIdxs = []int32{
	11, // 0: namenode_.StatDataResp.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	11, // 1: namenode_.DeleteDataResp.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	10, // 2: namenode_.NameNodeMetaData.blockAddresses:type_name -> namenode_.DataNodeInstance
	11, // 3: namenode_.ReadResponse.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	11, // 4: namenode_.WriteResponse.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	12, // 5: namenode_.NameNodeService.GetBlockSize:input_type -> namenode_.GetBlockSizeRequest
	14, // 6: namenode_.NameNodeService.ReadData:input_type -> namenode_.ReadRequst
	16, // 7: namenode_.NameNodeService.WriteData:input_type -> namenode_.WriteRequest
	8,  // 8: namenode_.NameNodeService.DeleteData:input_type -> namenode_.DeleteDataReq
	6,  // 9: namenode_.NameNodeService.StatData:input_type -> namenode_.StatDataReq
	4,  // 10: namenode_.NameNodeService.GetDataNodes:input_type -> namenode_.GetDataNodesReq
	2,  // 11: namenode_.NameNodeService.IsDir:input_type -> namenode_.IsDirReq
	0,  // 12: namenode_.NameNodeService.Rename:input_type -> namenode_.RenameReq
	13, // 13: namenode_.NameNodeService.GetBlockSize:output_type -> namenode_.GetBlockSizeResponse
	15, // 14: namenode_.NameNodeService.ReadData:output_type -> namenode_.ReadResponse
	17, // 15: namenode_.NameNodeService.WriteData:output_type -> namenode_.WriteResponse
	9,  // 16: namenode_.NameNodeService.DeleteData:output_type -> namenode_.DeleteDataResp
	7,  // 17: namenode_.NameNodeService.StatData:output_type -> namenode_.StatDataResp
	5,  // 18: namenode_.NameNodeService.GetDataNodes:output_type -> namenode_.GetDataNodesResp
	3,  // 19: namenode_.NameNodeService.IsDir:output_type -> namenode_.IsDirResp
	1,  // 20: namenode_.NameNodeService.Rename:output_type -> namenode_.RenameResp
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_namenode_namenode_proto_init() }
func file_proto_namenode_namenode_proto_init() {
	if File_proto_namenode_namenode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_namenode_namenode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsDirResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataNodeInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameNodeMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockSizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockSizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_namenode_namenode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namenode_namenode_proto_goTypes,
		DependencyIndexes: file_proto_namenode_namenode_proto_depIdxs,
		MessageInfos:      file_proto_namenode_namenode_proto_msgTypes,
	}.Build()
	File_proto_namenode_namenode_proto = out.File
	file_proto_namenode_namenode_proto_rawDesc = nil
	file_proto_namenode_namenode_proto_goTypes = nil
	file_proto_namenode_namenode_proto_depIdxs = nil
}
