// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: namenode/namenode.proto

package namenode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NameNodeServiceClient is the client API for NameNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameNodeServiceClient interface {
	//EC
	ECAssignDataNode(ctx context.Context, in *ECAssignDataNodeReq, opts ...grpc.CallOption) (*ECAssignDataNodeResp, error)
	GetBlockSize(ctx context.Context, in *GetBlockSizeRequest, opts ...grpc.CallOption) (*GetBlockSizeResponse, error)
	ReadData(ctx context.Context, in *ReadRequst, opts ...grpc.CallOption) (*ReadResponse, error)
	WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	DeleteData(ctx context.Context, in *DeleteDataReq, opts ...grpc.CallOption) (*DeleteDataResp, error)
	StatData(ctx context.Context, in *StatDataReq, opts ...grpc.CallOption) (*StatDataResp, error)
	GetDataNodes(ctx context.Context, in *GetDataNodesReq, opts ...grpc.CallOption) (*GetDataNodesResp, error)
	IsDir(ctx context.Context, in *IsDirReq, opts ...grpc.CallOption) (*IsDirResp, error)
	Rename(ctx context.Context, in *RenameReq, opts ...grpc.CallOption) (*RenameResp, error)
	Mkdir(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*MkdirResp, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	ReDirTree(ctx context.Context, in *ReDirTreeReq, opts ...grpc.CallOption) (*ReDirTreeResp, error)
	HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatResp, error)
	RegisterDataNode(ctx context.Context, in *RegisterDataNodeReq, opts ...grpc.CallOption) (*RegisterDataNodeResp, error)
	JoinCluster(ctx context.Context, in *JoinClusterReq, opts ...grpc.CallOption) (*JoinClusterResp, error)
	FindLeader(ctx context.Context, in *FindLeaderReq, opts ...grpc.CallOption) (*FindLeaderResp, error)
	UpdateDataNodeMessage(ctx context.Context, in *UpdateDataNodeMessageReq, opts ...grpc.CallOption) (*UpdateDataNodeMessageResp, error)
}

type nameNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameNodeServiceClient(cc grpc.ClientConnInterface) NameNodeServiceClient {
	return &nameNodeServiceClient{cc}
}

func (c *nameNodeServiceClient) ECAssignDataNode(ctx context.Context, in *ECAssignDataNodeReq, opts ...grpc.CallOption) (*ECAssignDataNodeResp, error) {
	out := new(ECAssignDataNodeResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/ECAssignDataNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) GetBlockSize(ctx context.Context, in *GetBlockSizeRequest, opts ...grpc.CallOption) (*GetBlockSizeResponse, error) {
	out := new(GetBlockSizeResponse)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/GetBlockSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) ReadData(ctx context.Context, in *ReadRequst, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/ReadData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/WriteData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) DeleteData(ctx context.Context, in *DeleteDataReq, opts ...grpc.CallOption) (*DeleteDataResp, error) {
	out := new(DeleteDataResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/DeleteData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) StatData(ctx context.Context, in *StatDataReq, opts ...grpc.CallOption) (*StatDataResp, error) {
	out := new(StatDataResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/StatData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) GetDataNodes(ctx context.Context, in *GetDataNodesReq, opts ...grpc.CallOption) (*GetDataNodesResp, error) {
	out := new(GetDataNodesResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/GetDataNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) IsDir(ctx context.Context, in *IsDirReq, opts ...grpc.CallOption) (*IsDirResp, error) {
	out := new(IsDirResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/IsDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) Rename(ctx context.Context, in *RenameReq, opts ...grpc.CallOption) (*RenameResp, error) {
	out := new(RenameResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) Mkdir(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*MkdirResp, error) {
	out := new(MkdirResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/Mkdir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) ReDirTree(ctx context.Context, in *ReDirTreeReq, opts ...grpc.CallOption) (*ReDirTreeResp, error) {
	out := new(ReDirTreeResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/ReDirTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatResp, error) {
	out := new(HeartBeatResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) RegisterDataNode(ctx context.Context, in *RegisterDataNodeReq, opts ...grpc.CallOption) (*RegisterDataNodeResp, error) {
	out := new(RegisterDataNodeResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/RegisterDataNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) JoinCluster(ctx context.Context, in *JoinClusterReq, opts ...grpc.CallOption) (*JoinClusterResp, error) {
	out := new(JoinClusterResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) FindLeader(ctx context.Context, in *FindLeaderReq, opts ...grpc.CallOption) (*FindLeaderResp, error) {
	out := new(FindLeaderResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/FindLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameNodeServiceClient) UpdateDataNodeMessage(ctx context.Context, in *UpdateDataNodeMessageReq, opts ...grpc.CallOption) (*UpdateDataNodeMessageResp, error) {
	out := new(UpdateDataNodeMessageResp)
	err := c.cc.Invoke(ctx, "/namenode_.NameNodeService/UpdateDataNodeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameNodeServiceServer is the server API for NameNodeService service.
// All implementations must embed UnimplementedNameNodeServiceServer
// for forward compatibility
type NameNodeServiceServer interface {
	//EC
	ECAssignDataNode(context.Context, *ECAssignDataNodeReq) (*ECAssignDataNodeResp, error)
	GetBlockSize(context.Context, *GetBlockSizeRequest) (*GetBlockSizeResponse, error)
	ReadData(context.Context, *ReadRequst) (*ReadResponse, error)
	WriteData(context.Context, *WriteRequest) (*WriteResponse, error)
	DeleteData(context.Context, *DeleteDataReq) (*DeleteDataResp, error)
	StatData(context.Context, *StatDataReq) (*StatDataResp, error)
	GetDataNodes(context.Context, *GetDataNodesReq) (*GetDataNodesResp, error)
	IsDir(context.Context, *IsDirReq) (*IsDirResp, error)
	Rename(context.Context, *RenameReq) (*RenameResp, error)
	Mkdir(context.Context, *MkdirReq) (*MkdirResp, error)
	List(context.Context, *ListReq) (*ListResp, error)
	ReDirTree(context.Context, *ReDirTreeReq) (*ReDirTreeResp, error)
	HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatResp, error)
	RegisterDataNode(context.Context, *RegisterDataNodeReq) (*RegisterDataNodeResp, error)
	JoinCluster(context.Context, *JoinClusterReq) (*JoinClusterResp, error)
	FindLeader(context.Context, *FindLeaderReq) (*FindLeaderResp, error)
	UpdateDataNodeMessage(context.Context, *UpdateDataNodeMessageReq) (*UpdateDataNodeMessageResp, error)
	mustEmbedUnimplementedNameNodeServiceServer()
}

// UnimplementedNameNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNameNodeServiceServer struct {
}

func (UnimplementedNameNodeServiceServer) ECAssignDataNode(context.Context, *ECAssignDataNodeReq) (*ECAssignDataNodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ECAssignDataNode not implemented")
}
func (UnimplementedNameNodeServiceServer) GetBlockSize(context.Context, *GetBlockSizeRequest) (*GetBlockSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockSize not implemented")
}
func (UnimplementedNameNodeServiceServer) ReadData(context.Context, *ReadRequst) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedNameNodeServiceServer) WriteData(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteData not implemented")
}
func (UnimplementedNameNodeServiceServer) DeleteData(context.Context, *DeleteDataReq) (*DeleteDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedNameNodeServiceServer) StatData(context.Context, *StatDataReq) (*StatDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatData not implemented")
}
func (UnimplementedNameNodeServiceServer) GetDataNodes(context.Context, *GetDataNodesReq) (*GetDataNodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataNodes not implemented")
}
func (UnimplementedNameNodeServiceServer) IsDir(context.Context, *IsDirReq) (*IsDirResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsDir not implemented")
}
func (UnimplementedNameNodeServiceServer) Rename(context.Context, *RenameReq) (*RenameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedNameNodeServiceServer) Mkdir(context.Context, *MkdirReq) (*MkdirResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedNameNodeServiceServer) List(context.Context, *ListReq) (*ListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNameNodeServiceServer) ReDirTree(context.Context, *ReDirTreeReq) (*ReDirTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReDirTree not implemented")
}
func (UnimplementedNameNodeServiceServer) HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedNameNodeServiceServer) RegisterDataNode(context.Context, *RegisterDataNodeReq) (*RegisterDataNodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDataNode not implemented")
}
func (UnimplementedNameNodeServiceServer) JoinCluster(context.Context, *JoinClusterReq) (*JoinClusterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedNameNodeServiceServer) FindLeader(context.Context, *FindLeaderReq) (*FindLeaderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLeader not implemented")
}
func (UnimplementedNameNodeServiceServer) UpdateDataNodeMessage(context.Context, *UpdateDataNodeMessageReq) (*UpdateDataNodeMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDataNodeMessage not implemented")
}
func (UnimplementedNameNodeServiceServer) mustEmbedUnimplementedNameNodeServiceServer() {}

// UnsafeNameNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameNodeServiceServer will
// result in compilation errors.
type UnsafeNameNodeServiceServer interface {
	mustEmbedUnimplementedNameNodeServiceServer()
}

func RegisterNameNodeServiceServer(s grpc.ServiceRegistrar, srv NameNodeServiceServer) {
	s.RegisterService(&NameNodeService_ServiceDesc, srv)
}

func _NameNodeService_ECAssignDataNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ECAssignDataNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).ECAssignDataNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/ECAssignDataNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).ECAssignDataNode(ctx, req.(*ECAssignDataNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_GetBlockSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).GetBlockSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/GetBlockSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).GetBlockSize(ctx, req.(*GetBlockSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_ReadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).ReadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/ReadData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).ReadData(ctx, req.(*ReadRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_WriteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).WriteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/WriteData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).WriteData(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/DeleteData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).DeleteData(ctx, req.(*DeleteDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_StatData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).StatData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/StatData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).StatData(ctx, req.(*StatDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_GetDataNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataNodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).GetDataNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/GetDataNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).GetDataNodes(ctx, req.(*GetDataNodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_IsDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsDirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).IsDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/IsDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).IsDir(ctx, req.(*IsDirReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).Rename(ctx, req.(*RenameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/Mkdir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).Mkdir(ctx, req.(*MkdirReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_ReDirTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReDirTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).ReDirTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/ReDirTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).ReDirTree(ctx, req.(*ReDirTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).HeartBeat(ctx, req.(*HeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_RegisterDataNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).RegisterDataNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/RegisterDataNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).RegisterDataNode(ctx, req.(*RegisterDataNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).JoinCluster(ctx, req.(*JoinClusterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_FindLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLeaderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).FindLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/FindLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).FindLeader(ctx, req.(*FindLeaderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameNodeService_UpdateDataNodeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataNodeMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeServiceServer).UpdateDataNodeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode_.NameNodeService/UpdateDataNodeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeServiceServer).UpdateDataNodeMessage(ctx, req.(*UpdateDataNodeMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NameNodeService_ServiceDesc is the grpc.ServiceDesc for NameNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namenode_.NameNodeService",
	HandlerType: (*NameNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ECAssignDataNode",
			Handler:    _NameNodeService_ECAssignDataNode_Handler,
		},
		{
			MethodName: "GetBlockSize",
			Handler:    _NameNodeService_GetBlockSize_Handler,
		},
		{
			MethodName: "ReadData",
			Handler:    _NameNodeService_ReadData_Handler,
		},
		{
			MethodName: "WriteData",
			Handler:    _NameNodeService_WriteData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _NameNodeService_DeleteData_Handler,
		},
		{
			MethodName: "StatData",
			Handler:    _NameNodeService_StatData_Handler,
		},
		{
			MethodName: "GetDataNodes",
			Handler:    _NameNodeService_GetDataNodes_Handler,
		},
		{
			MethodName: "IsDir",
			Handler:    _NameNodeService_IsDir_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _NameNodeService_Rename_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _NameNodeService_Mkdir_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NameNodeService_List_Handler,
		},
		{
			MethodName: "ReDirTree",
			Handler:    _NameNodeService_ReDirTree_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _NameNodeService_HeartBeat_Handler,
		},
		{
			MethodName: "RegisterDataNode",
			Handler:    _NameNodeService_RegisterDataNode_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _NameNodeService_JoinCluster_Handler,
		},
		{
			MethodName: "FindLeader",
			Handler:    _NameNodeService_FindLeader_Handler,
		},
		{
			MethodName: "UpdateDataNodeMessage",
			Handler:    _NameNodeService_UpdateDataNodeMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "namenode/namenode.proto",
}
