// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/namenode/namenode.proto

package namenode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECAssignDataNodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename       string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	DatanodeNumber int64  `protobuf:"varint,2,opt,name=datanodeNumber,proto3" json:"datanodeNumber,omitempty"`
}

func (x *ECAssignDataNodeReq) Reset() {
	*x = ECAssignDataNodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECAssignDataNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECAssignDataNodeReq) ProtoMessage() {}

func (x *ECAssignDataNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECAssignDataNodeReq.ProtoReflect.Descriptor instead.
func (*ECAssignDataNodeReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *ECAssignDataNodeReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ECAssignDataNodeReq) GetDatanodeNumber() int64 {
	if x != nil {
		return x.DatanodeNumber
	}
	return 0
}

type ECAssignDataNodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaData []*NameNodeMetaData `protobuf:"bytes,1,rep,name=NameNodeMetaData,proto3" json:"NameNodeMetaData,omitempty"`
}

func (x *ECAssignDataNodeResp) Reset() {
	*x = ECAssignDataNodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECAssignDataNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECAssignDataNodeResp) ProtoMessage() {}

func (x *ECAssignDataNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECAssignDataNodeResp.ProtoReflect.Descriptor instead.
func (*ECAssignDataNodeResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *ECAssignDataNodeResp) GetNameNodeMetaData() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaData
	}
	return nil
}

type FindLeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindLeaderReq) Reset() {
	*x = FindLeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLeaderReq) ProtoMessage() {}

func (x *FindLeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLeaderReq.ProtoReflect.Descriptor instead.
func (*FindLeaderReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{2}
}

type FindLeaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *FindLeaderResp) Reset() {
	*x = FindLeaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLeaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLeaderResp) ProtoMessage() {}

func (x *FindLeaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLeaderResp.ProtoReflect.Descriptor instead.
func (*FindLeaderResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{3}
}

func (x *FindLeaderResp) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type JoinClusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Addr          string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	PreviousIndex uint64 `protobuf:"varint,3,opt,name=PreviousIndex,proto3" json:"PreviousIndex,omitempty"`
}

func (x *JoinClusterReq) Reset() {
	*x = JoinClusterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterReq) ProtoMessage() {}

func (x *JoinClusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterReq.ProtoReflect.Descriptor instead.
func (*JoinClusterReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{4}
}

func (x *JoinClusterReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinClusterReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *JoinClusterReq) GetPreviousIndex() uint64 {
	if x != nil {
		return x.PreviousIndex
	}
	return 0
}

type JoinClusterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *JoinClusterResp) Reset() {
	*x = JoinClusterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinClusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResp) ProtoMessage() {}

func (x *JoinClusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResp.ProtoReflect.Descriptor instead.
func (*JoinClusterResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{5}
}

func (x *JoinClusterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateDataNodeMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string  `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	UsedDisk   uint64  `protobuf:"varint,2,opt,name=UsedDisk,proto3" json:"UsedDisk,omitempty"`
	UsedMem    uint64  `protobuf:"varint,3,opt,name=UsedMem,proto3" json:"UsedMem,omitempty"`
	CpuPercent float32 `protobuf:"fixed32,4,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	TotalMem   uint64  `protobuf:"varint,5,opt,name=TotalMem,proto3" json:"TotalMem,omitempty"`
	TotalDisk  uint64  `protobuf:"varint,6,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
}

func (x *UpdateDataNodeMessageReq) Reset() {
	*x = UpdateDataNodeMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataNodeMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataNodeMessageReq) ProtoMessage() {}

func (x *UpdateDataNodeMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataNodeMessageReq.ProtoReflect.Descriptor instead.
func (*UpdateDataNodeMessageReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDataNodeMessageReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *UpdateDataNodeMessageReq) GetUsedDisk() uint64 {
	if x != nil {
		return x.UsedDisk
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetUsedMem() uint64 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetTotalMem() uint64 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *UpdateDataNodeMessageReq) GetTotalDisk() uint64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

type UpdateDataNodeMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *UpdateDataNodeMessageResp) Reset() {
	*x = UpdateDataNodeMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDataNodeMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataNodeMessageResp) ProtoMessage() {}

func (x *UpdateDataNodeMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataNodeMessageResp.ProtoReflect.Descriptor instead.
func (*UpdateDataNodeMessageResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDataNodeMessageResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterDataNodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr       string  `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	UsedDisk   uint64  `protobuf:"varint,2,opt,name=UsedDisk,proto3" json:"UsedDisk,omitempty"`
	UsedMem    uint64  `protobuf:"varint,3,opt,name=UsedMem,proto3" json:"UsedMem,omitempty"`
	CpuPercent float32 `protobuf:"fixed32,4,opt,name=CpuPercent,proto3" json:"CpuPercent,omitempty"`
	TotalMem   uint64  `protobuf:"varint,5,opt,name=TotalMem,proto3" json:"TotalMem,omitempty"`
	TotalDisk  uint64  `protobuf:"varint,6,opt,name=TotalDisk,proto3" json:"TotalDisk,omitempty"`
}

func (x *RegisterDataNodeReq) Reset() {
	*x = RegisterDataNodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDataNodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataNodeReq) ProtoMessage() {}

func (x *RegisterDataNodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataNodeReq.ProtoReflect.Descriptor instead.
func (*RegisterDataNodeReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterDataNodeReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterDataNodeReq) GetUsedDisk() uint64 {
	if x != nil {
		return x.UsedDisk
	}
	return 0
}

func (x *RegisterDataNodeReq) GetUsedMem() uint64 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *RegisterDataNodeReq) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *RegisterDataNodeReq) GetTotalMem() uint64 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *RegisterDataNodeReq) GetTotalDisk() uint64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

type RegisterDataNodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *RegisterDataNodeResp) Reset() {
	*x = RegisterDataNodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDataNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataNodeResp) ProtoMessage() {}

func (x *RegisterDataNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataNodeResp.ProtoReflect.Descriptor instead.
func (*RegisterDataNodeResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterDataNodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartBeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *HeartBeatReq) Reset() {
	*x = HeartBeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatReq) ProtoMessage() {}

func (x *HeartBeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatReq.ProtoReflect.Descriptor instead.
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{10}
}

func (x *HeartBeatReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type HeartBeatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *HeartBeatResp) Reset() {
	*x = HeartBeatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResp) ProtoMessage() {}

func (x *HeartBeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResp.ProtoReflect.Descriptor instead.
func (*HeartBeatResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{11}
}

func (x *HeartBeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentPath string `protobuf:"bytes,1,opt,name=ParentPath,proto3" json:"ParentPath,omitempty"`
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{12}
}

func (x *ListReq) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

type ListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DirName  []string `protobuf:"bytes,1,rep,name=DirName,proto3" json:"DirName,omitempty"`
	FileName []string `protobuf:"bytes,2,rep,name=FileName,proto3" json:"FileName,omitempty"`
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{13}
}

func (x *ListResp) GetDirName() []string {
	if x != nil {
		return x.DirName
	}
	return nil
}

func (x *ListResp) GetFileName() []string {
	if x != nil {
		return x.FileName
	}
	return nil
}

type MkdirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *MkdirReq) Reset() {
	*x = MkdirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkdirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirReq) ProtoMessage() {}

func (x *MkdirReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirReq.ProtoReflect.Descriptor instead.
func (*MkdirReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{14}
}

func (x *MkdirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MkdirResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MkdirResp) Reset() {
	*x = MkdirResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkdirResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResp) ProtoMessage() {}

func (x *MkdirResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResp.ProtoReflect.Descriptor instead.
func (*MkdirResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{15}
}

type ReDirTreeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldPath string `protobuf:"bytes,1,opt,name=OldPath,proto3" json:"OldPath,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=NewPath,proto3" json:"NewPath,omitempty"`
}

func (x *ReDirTreeReq) Reset() {
	*x = ReDirTreeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReDirTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReDirTreeReq) ProtoMessage() {}

func (x *ReDirTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReDirTreeReq.ProtoReflect.Descriptor instead.
func (*ReDirTreeReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{16}
}

func (x *ReDirTreeReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *ReDirTreeReq) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type ReDirTreeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *ReDirTreeResp) Reset() {
	*x = ReDirTreeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReDirTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReDirTreeResp) ProtoMessage() {}

func (x *ReDirTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReDirTreeResp.ProtoReflect.Descriptor instead.
func (*ReDirTreeResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{17}
}

func (x *ReDirTreeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RenameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldFileName string `protobuf:"bytes,1,opt,name=OldFileName,proto3" json:"OldFileName,omitempty"`
	NewFileName string `protobuf:"bytes,2,opt,name=NewFileName,proto3" json:"NewFileName,omitempty"`
}

func (x *RenameReq) Reset() {
	*x = RenameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReq) ProtoMessage() {}

func (x *RenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReq.ProtoReflect.Descriptor instead.
func (*RenameReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{18}
}

func (x *RenameReq) GetOldFileName() string {
	if x != nil {
		return x.OldFileName
	}
	return ""
}

func (x *RenameReq) GetNewFileName() string {
	if x != nil {
		return x.NewFileName
	}
	return ""
}

type RenameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *RenameResp) Reset() {
	*x = RenameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResp) ProtoMessage() {}

func (x *RenameResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResp.ProtoReflect.Descriptor instead.
func (*RenameResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{19}
}

func (x *RenameResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IsDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
}

func (x *IsDirReq) Reset() {
	*x = IsDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDirReq) ProtoMessage() {}

func (x *IsDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDirReq.ProtoReflect.Descriptor instead.
func (*IsDirReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{20}
}

func (x *IsDirReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type IsDirResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *IsDirResp) Reset() {
	*x = IsDirResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDirResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDirResp) ProtoMessage() {}

func (x *IsDirResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDirResp.ProtoReflect.Descriptor instead.
func (*IsDirResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{21}
}

func (x *IsDirResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetDataNodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDataNodesReq) Reset() {
	*x = GetDataNodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataNodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataNodesReq) ProtoMessage() {}

func (x *GetDataNodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataNodesReq.ProtoReflect.Descriptor instead.
func (*GetDataNodesReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{22}
}

type GetDataNodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataNodeList []string `protobuf:"bytes,1,rep,name=DataNodeList,proto3" json:"DataNodeList,omitempty"`
}

func (x *GetDataNodesResp) Reset() {
	*x = GetDataNodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataNodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataNodesResp) ProtoMessage() {}

func (x *GetDataNodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataNodesResp.ProtoReflect.Descriptor instead.
func (*GetDataNodesResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{23}
}

func (x *GetDataNodesResp) GetDataNodeList() []string {
	if x != nil {
		return x.DataNodeList
	}
	return nil
}

type StatDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *StatDataReq) Reset() {
	*x = StatDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDataReq) ProtoMessage() {}

func (x *StatDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDataReq.ProtoReflect.Descriptor instead.
func (*StatDataReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{24}
}

func (x *StatDataReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type StatDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *StatDataResp) Reset() {
	*x = StatDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDataResp) ProtoMessage() {}

func (x *StatDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDataResp.ProtoReflect.Descriptor instead.
func (*StatDataResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{25}
}

func (x *StatDataResp) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

type DeleteDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *DeleteDataReq) Reset() {
	*x = DeleteDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataReq) ProtoMessage() {}

func (x *DeleteDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataReq.ProtoReflect.Descriptor instead.
func (*DeleteDataReq) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteDataReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type DeleteDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *DeleteDataResp) Reset() {
	*x = DeleteDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResp) ProtoMessage() {}

func (x *DeleteDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResp.ProtoReflect.Descriptor instead.
func (*DeleteDataResp) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteDataResp) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

type DataNodeInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host        string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ServicePort string `protobuf:"bytes,2,opt,name=servicePort,proto3" json:"servicePort,omitempty"`
}

func (x *DataNodeInstance) Reset() {
	*x = DataNodeInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataNodeInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNodeInstance) ProtoMessage() {}

func (x *DataNodeInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNodeInstance.ProtoReflect.Descriptor instead.
func (*DataNodeInstance) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{28}
}

func (x *DataNodeInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DataNodeInstance) GetServicePort() string {
	if x != nil {
		return x.ServicePort
	}
	return ""
}

type NameNodeMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId        string              `protobuf:"bytes,1,opt,name=blockId,proto3" json:"blockId,omitempty"`
	BlockAddresses []*DataNodeInstance `protobuf:"bytes,2,rep,name=blockAddresses,proto3" json:"blockAddresses,omitempty"`
}

func (x *NameNodeMetaData) Reset() {
	*x = NameNodeMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameNodeMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameNodeMetaData) ProtoMessage() {}

func (x *NameNodeMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameNodeMetaData.ProtoReflect.Descriptor instead.
func (*NameNodeMetaData) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{29}
}

func (x *NameNodeMetaData) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NameNodeMetaData) GetBlockAddresses() []*DataNodeInstance {
	if x != nil {
		return x.BlockAddresses
	}
	return nil
}

type GetBlockSizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request bool `protobuf:"varint,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetBlockSizeRequest) Reset() {
	*x = GetBlockSizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockSizeRequest) ProtoMessage() {}

func (x *GetBlockSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockSizeRequest.ProtoReflect.Descriptor instead.
func (*GetBlockSizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{30}
}

func (x *GetBlockSizeRequest) GetRequest() bool {
	if x != nil {
		return x.Request
	}
	return false
}

type GetBlockSizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockSize uint64 `protobuf:"varint,1,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
}

func (x *GetBlockSizeResponse) Reset() {
	*x = GetBlockSizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockSizeResponse) ProtoMessage() {}

func (x *GetBlockSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockSizeResponse.ProtoReflect.Descriptor instead.
func (*GetBlockSizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{31}
}

func (x *GetBlockSizeResponse) GetBlockSize() uint64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type ReadRequst struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *ReadRequst) Reset() {
	*x = ReadRequst{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequst) ProtoMessage() {}

func (x *ReadRequst) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequst.ProtoReflect.Descriptor instead.
func (*ReadRequst) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{32}
}

func (x *ReadRequst) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{33}
}

func (x *ReadResponse) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber uint64 `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	FileName    string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{34}
}

func (x *WriteRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *WriteRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameNodeMetaDataList []*NameNodeMetaData `protobuf:"bytes,1,rep,name=nameNodeMetaDataList,proto3" json:"nameNodeMetaDataList,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_namenode_namenode_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_namenode_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_namenode_proto_rawDescGZIP(), []int{35}
}

func (x *WriteResponse) GetNameNodeMetaDataList() []*NameNodeMetaData {
	if x != nil {
		return x.NameNodeMetaDataList
	}
	return nil
}

var File_proto_namenode_namenode_proto protoreflect.FileDescriptor

var file_proto_namenode_namenode_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x22, 0x59, 0x0a, 0x13, 0x45, 0x43,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x5f, 0x0a, 0x14, 0x45, 0x43, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47, 0x0a,
	0x10, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x24, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x5a, 0x0a,
	0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x50, 0x72, 0x65, 0x76,
	0x69, 0x6f, 0x75, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2b, 0x0a, 0x0f, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x64, 0x44,
	0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x55, 0x73, 0x65, 0x64, 0x44,
	0x69, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x22, 0x35, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xb9,
	0x01, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x64, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x43, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x0c,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72,
	0x22, 0x29, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x07, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x22, 0x40, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x44, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x4d, 0x6b, 0x64, 0x69,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x22, 0x0b, 0x0a, 0x09, 0x4d, 0x6b, 0x64, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x42, 0x0a, 0x0c, 0x52, 0x65, 0x44, 0x69, 0x72, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x74, 0x68, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x44,
	0x69, 0x72, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x4f, 0x0a, 0x09, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a,
	0x08, 0x49, 0x73, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x09, 0x49, 0x73, 0x44, 0x69, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x4f, 0x6b, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x29, 0x0a,
	0x0b, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x10, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x6f, 0x72, 0x74, 0x22, 0x71, 0x0a, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x64, 0x12, 0x43, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x28, 0x0a,
	0x0a, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x14, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x9a, 0x09, 0x0a, 0x0f, 0x4e, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x10,
	0x45, 0x43, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x45, 0x43, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1f, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x45, 0x43, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x4f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1e, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15,
	0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x09, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x6e,
	0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3b, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a,
	0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72,
	0x12, 0x13, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x49, 0x73, 0x44,
	0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x49, 0x73, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x06, 0x52,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x32, 0x0a, 0x05, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x12, 0x13, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4d, 0x6b, 0x64,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x09, 0x52, 0x65, 0x44, 0x69, 0x72,
	0x54, 0x72, 0x65, 0x65, 0x12, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x2e, 0x52, 0x65, 0x44, 0x69, 0x72, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x44, 0x69, 0x72, 0x54,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x12, 0x17, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x57, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x48, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x19, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0a, 0x46, 0x69,
	0x6e, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x62, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x2e, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x6f, 0x2d, 0x66, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_namenode_namenode_proto_rawDescOnce sync.Once
	file_proto_namenode_namenode_proto_rawDescData = file_proto_namenode_namenode_proto_rawDesc
)

func file_proto_namenode_namenode_proto_rawDescGZIP() []byte {
	file_proto_namenode_namenode_proto_rawDescOnce.Do(func() {
		file_proto_namenode_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_namenode_namenode_proto_rawDescData)
	})
	return file_proto_namenode_namenode_proto_rawDescData
}

var file_proto_namenode_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_namenode_namenode_proto_goTypes = []interface{}{
	(*ECAssignDataNodeReq)(nil),       // 0: namenode_.ECAssignDataNodeReq
	(*ECAssignDataNodeResp)(nil),      // 1: namenode_.ECAssignDataNodeResp
	(*FindLeaderReq)(nil),             // 2: namenode_.FindLeaderReq
	(*FindLeaderResp)(nil),            // 3: namenode_.FindLeaderResp
	(*JoinClusterReq)(nil),            // 4: namenode_.JoinClusterReq
	(*JoinClusterResp)(nil),           // 5: namenode_.JoinClusterResp
	(*UpdateDataNodeMessageReq)(nil),  // 6: namenode_.UpdateDataNodeMessageReq
	(*UpdateDataNodeMessageResp)(nil), // 7: namenode_.UpdateDataNodeMessageResp
	(*RegisterDataNodeReq)(nil),       // 8: namenode_.RegisterDataNodeReq
	(*RegisterDataNodeResp)(nil),      // 9: namenode_.RegisterDataNodeResp
	(*HeartBeatReq)(nil),              // 10: namenode_.HeartBeatReq
	(*HeartBeatResp)(nil),             // 11: namenode_.HeartBeatResp
	(*ListReq)(nil),                   // 12: namenode_.ListReq
	(*ListResp)(nil),                  // 13: namenode_.ListResp
	(*MkdirReq)(nil),                  // 14: namenode_.MkdirReq
	(*MkdirResp)(nil),                 // 15: namenode_.MkdirResp
	(*ReDirTreeReq)(nil),              // 16: namenode_.ReDirTreeReq
	(*ReDirTreeResp)(nil),             // 17: namenode_.ReDirTreeResp
	(*RenameReq)(nil),                 // 18: namenode_.RenameReq
	(*RenameResp)(nil),                // 19: namenode_.RenameResp
	(*IsDirReq)(nil),                  // 20: namenode_.IsDirReq
	(*IsDirResp)(nil),                 // 21: namenode_.IsDirResp
	(*GetDataNodesReq)(nil),           // 22: namenode_.GetDataNodesReq
	(*GetDataNodesResp)(nil),          // 23: namenode_.GetDataNodesResp
	(*StatDataReq)(nil),               // 24: namenode_.StatDataReq
	(*StatDataResp)(nil),              // 25: namenode_.StatDataResp
	(*DeleteDataReq)(nil),             // 26: namenode_.DeleteDataReq
	(*DeleteDataResp)(nil),            // 27: namenode_.DeleteDataResp
	(*DataNodeInstance)(nil),          // 28: namenode_.DataNodeInstance
	(*NameNodeMetaData)(nil),          // 29: namenode_.NameNodeMetaData
	(*GetBlockSizeRequest)(nil),       // 30: namenode_.GetBlockSizeRequest
	(*GetBlockSizeResponse)(nil),      // 31: namenode_.GetBlockSizeResponse
	(*ReadRequst)(nil),                // 32: namenode_.ReadRequst
	(*ReadResponse)(nil),              // 33: namenode_.ReadResponse
	(*WriteRequest)(nil),              // 34: namenode_.WriteRequest
	(*WriteResponse)(nil),             // 35: namenode_.WriteResponse
}
var file_proto_namenode_namenode_proto_depIdxs = []int32{
	29, // 0: namenode_.ECAssignDataNodeResp.NameNodeMetaData:type_name -> namenode_.NameNodeMetaData
	29, // 1: namenode_.StatDataResp.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	29, // 2: namenode_.DeleteDataResp.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	28, // 3: namenode_.NameNodeMetaData.blockAddresses:type_name -> namenode_.DataNodeInstance
	29, // 4: namenode_.ReadResponse.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	29, // 5: namenode_.WriteResponse.nameNodeMetaDataList:type_name -> namenode_.NameNodeMetaData
	0,  // 6: namenode_.NameNodeService.ECAssignDataNode:input_type -> namenode_.ECAssignDataNodeReq
	30, // 7: namenode_.NameNodeService.GetBlockSize:input_type -> namenode_.GetBlockSizeRequest
	32, // 8: namenode_.NameNodeService.ReadData:input_type -> namenode_.ReadRequst
	34, // 9: namenode_.NameNodeService.WriteData:input_type -> namenode_.WriteRequest
	26, // 10: namenode_.NameNodeService.DeleteData:input_type -> namenode_.DeleteDataReq
	24, // 11: namenode_.NameNodeService.StatData:input_type -> namenode_.StatDataReq
	22, // 12: namenode_.NameNodeService.GetDataNodes:input_type -> namenode_.GetDataNodesReq
	20, // 13: namenode_.NameNodeService.IsDir:input_type -> namenode_.IsDirReq
	18, // 14: namenode_.NameNodeService.Rename:input_type -> namenode_.RenameReq
	14, // 15: namenode_.NameNodeService.Mkdir:input_type -> namenode_.MkdirReq
	12, // 16: namenode_.NameNodeService.List:input_type -> namenode_.ListReq
	16, // 17: namenode_.NameNodeService.ReDirTree:input_type -> namenode_.ReDirTreeReq
	10, // 18: namenode_.NameNodeService.HeartBeat:input_type -> namenode_.HeartBeatReq
	8,  // 19: namenode_.NameNodeService.RegisterDataNode:input_type -> namenode_.RegisterDataNodeReq
	4,  // 20: namenode_.NameNodeService.JoinCluster:input_type -> namenode_.JoinClusterReq
	2,  // 21: namenode_.NameNodeService.FindLeader:input_type -> namenode_.FindLeaderReq
	6,  // 22: namenode_.NameNodeService.UpdateDataNodeMessage:input_type -> namenode_.UpdateDataNodeMessageReq
	1,  // 23: namenode_.NameNodeService.ECAssignDataNode:output_type -> namenode_.ECAssignDataNodeResp
	31, // 24: namenode_.NameNodeService.GetBlockSize:output_type -> namenode_.GetBlockSizeResponse
	33, // 25: namenode_.NameNodeService.ReadData:output_type -> namenode_.ReadResponse
	35, // 26: namenode_.NameNodeService.WriteData:output_type -> namenode_.WriteResponse
	27, // 27: namenode_.NameNodeService.DeleteData:output_type -> namenode_.DeleteDataResp
	25, // 28: namenode_.NameNodeService.StatData:output_type -> namenode_.StatDataResp
	23, // 29: namenode_.NameNodeService.GetDataNodes:output_type -> namenode_.GetDataNodesResp
	21, // 30: namenode_.NameNodeService.IsDir:output_type -> namenode_.IsDirResp
	19, // 31: namenode_.NameNodeService.Rename:output_type -> namenode_.RenameResp
	15, // 32: namenode_.NameNodeService.Mkdir:output_type -> namenode_.MkdirResp
	13, // 33: namenode_.NameNodeService.List:output_type -> namenode_.ListResp
	17, // 34: namenode_.NameNodeService.ReDirTree:output_type -> namenode_.ReDirTreeResp
	11, // 35: namenode_.NameNodeService.HeartBeat:output_type -> namenode_.HeartBeatResp
	9,  // 36: namenode_.NameNodeService.RegisterDataNode:output_type -> namenode_.RegisterDataNodeResp
	5,  // 37: namenode_.NameNodeService.JoinCluster:output_type -> namenode_.JoinClusterResp
	3,  // 38: namenode_.NameNodeService.FindLeader:output_type -> namenode_.FindLeaderResp
	7,  // 39: namenode_.NameNodeService.UpdateDataNodeMessage:output_type -> namenode_.UpdateDataNodeMessageResp
	23, // [23:40] is the sub-list for method output_type
	6,  // [6:23] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_namenode_namenode_proto_init() }
func file_proto_namenode_namenode_proto_init() {
	if File_proto_namenode_namenode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_namenode_namenode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECAssignDataNodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECAssignDataNodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLeaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinClusterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataNodeMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDataNodeMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDataNodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDataNodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MkdirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MkdirResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReDirTreeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReDirTreeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsDirResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataNodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataNodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataNodeInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameNodeMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockSizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockSizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequst); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_namenode_namenode_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_namenode_namenode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namenode_namenode_proto_goTypes,
		DependencyIndexes: file_proto_namenode_namenode_proto_depIdxs,
		MessageInfos:      file_proto_namenode_namenode_proto_msgTypes,
	}.Build()
	File_proto_namenode_namenode_proto = out.File
	file_proto_namenode_namenode_proto_rawDesc = nil
	file_proto_namenode_namenode_proto_goTypes = nil
	file_proto_namenode_namenode_proto_depIdxs = nil
}
